version: "3.8"

services:

  client:
    container_name: client-dev
    image: client-dev
    build: .
    volumes:
      - ./src:/app/src
    # todo: not work correctly!
    # ports:
    #   - "3001"
    network_mode: host