import ArrowUpDownFillIcon from "remixicon-react/ArrowUpDownFillIcon";
import HonourLineIcon from "remixicon-react/HonourLineIcon";

export const swrOptions = {
  revalidateOnFocus: false,
  revalidateOnReconnect: false,
  refreshWhenOffline: false,
  refreshWhenHidden: false,
  refreshInterval: 0,
  shouldRetryOnError: false,
};
export const domain = "https://test.icarts.ir/";
export const faFieldOfWorkType = {
  ELECTRICAL_APPLIANCES_STORE: "لوازم برقی",
  HOME_APPLIANCES: "لوازم خانگی",
  FURNITURE_STORES: "مبلمان",
  BAKERY: "نانوایی",
  PROTEIN_STORE: "مواد پروتئینی",
  MOBILE: "فروشگاه موبایل",
  AUDIO_AND_VIDEO_PRODUCT_STORE: "محصولات صوتی و تصویری",
  KITCHEN_ACCESSORIES_STORE: " لوازم آشپزخانه",
  SLEEP_GOODS_STORES: " کالای خواب",
  GROCERY_STORES: "مواد غذایی",
  CHANDELIERS_AND_ELECTRICAL_APPLIANCES: "لوستر و لوازم برقی",
  STATIONERY_STORES: "لوازم التحریر",
  DTY_FRUITS_SHOP: "فروشگاه میوه خشک",
  CLINICS: "کلینیک",
  CLOTHING_STORES: "پوشاک",
  HAIRDRESSERS: "آرایشگران",
  LASER_CENTERS: "مراکز لیزر",
  GOLD_AND_SILVER: "طلا و نقره",
  WATCH_SHOP: "فروشگاه ساعت",
  PERFUME_AND_COLOGNE_STORE: "عطر و ادکلن",
  DECORATION: "دکوراسیون",
  COSMETIC: "آرایشی و بهداشتی",
  MESON: "مزون",
  CAR_REPAIRS: "تعمیرات خودرو",
  PHARMACY: "داروخانه",
  EDUCATIONAL_SERVICES: "خدمات آموزشی",
  BEAUTY_CLINICS: "کلینیک زیبایی",
  FACIAL_GEL_BOTOX: "فیشال ، ژل و بوتاکس",
  CARPET: "فرش",
  ELECTRICAL_APPLIANCES_REPAIRS: "تعمیرات کالای برقی",
  LAPTOP: "لپ تاپ",
  DIGITAL_ACCESSORIES: "لوازم جانبی",
  TRAVEL_AGENCY: "آژانس مسافرتی",
  RECREATIONAL_SPORTS_CENTERS: "مراکز تفریحی و ورزشی",
  LANGUAGE_TEACHING: "آموزش زبان",
  HAIRDRESSING_TRAINING: "آموزش آرایشگری",
  STATIONERY: "لوازم التحریر ",
  WATCH_GALLERY: "گالری ساعت",
  GOLD_SALES: "طلافروشی",
  JEWELRY_ACCESSORIES: "اکسسوری زیورآلات",
  SUPER_MARKET: "سوپرمارکت",
  FRUIT_SHOP: "میوه فروشی",
  DAIRY: "لبنیات",
  CAFE_RESTAURANT_FAST_FOOD: "کافه، رستوران و فست فود",
  CONFECTIONERY_DRIED_FRUIT: "قنادی و خشکبار",
  ASIA_INSURANCE: "بیمه آسیا",
  THIRD_PARTY_INSURANCE: "بیمه ثالث",
  ADULT_CLOTHING: "پوشاک بزرگسالان",
  CHILDREN_CLOTHING: "پوشاک کودکانه",
  BAGS_AND_SHOES: "کیف و کفش",
  INTERIOR_DECORATION_DESIGNER: "طراح دکوراسیون داخلی",
  BUILDING_EQUIPMENT: "لوازم ساختمانی",
};
export const enFieldOfWorkType = {
  "لوازم برقی": "ELECTRICAL_APPLIANCES_STORE",
  "لوازم خانگی": "HOME_APPLIANCES",
  مبلمان: "FURNITURE_STORES",
  "میوه فروشی": "FRUIT_SHOP",
  نانوایی: "BAKERY",
  "مواد پروتئینی": "PROTEIN_STORE",
  "فروشگاه موبایل": "MOBILE",
  "محصولات صوتی و تصویری": "AUDIO_AND_VIDEO_PRODUCT_STORE",
  " لوازم آشپزخانه": "KITCHEN_ACCESSORIES_STORE",
  " کالای خواب": "SLEEP_GOODS_STORES",
  "مواد غذایی": "GROCERY_STORES",
  "لوستر و لوازم برقی": "CHANDELIERS_AND_ELECTRICAL_APPLIANCES",
  "لوازم التحریر": "STATIONERY_STORES",
  "فروشگاه میوه خشک": "DTY_FRUITS_SHOP",
  "کلینیک زیبایی": "BEAUTY_CLINICS",
  کلینیک: "CLINICS",
  پوشاک: "CLOTHING_STORES",
  آرایشگران: "HAIRDRESSERS",
  "مراکز لیزر": "LASER_CENTERS",
  "طلا و نقره": "GOLD_AND_SILVER",
  "فروشگاه ساعت": "WATCH_SHOP",
  "عطر و ادکلن": "PERFUME_AND_COLOGNE_STORE",
  دکوراسیون: "DECORATION",
  "آرایشی و بهداشتی": "COSMETIC",
  مزون: "MESON",
  "تعمیرات خودرو": "CAR_REPAIRS",
  داروخانه: "PHARMACY",
  "خدمات آموزشی": "EDUCATIONAL_SERVICES",
  "فیشال ، ژل و بوتاکس": "FACIAL_GEL_BOTOX",
  فرش: "CARPET",
  "تعمیرات کالای برقی": "ELECTRICAL_APPLIANCES_REPAIRS",
  "لپ تاپ": "LAPTOP",
  "لوازم جانبی": "DIGITAL_ACCESSORIES",
  "آژانس مسافرتی": "TRAVEL_AGENCY",
  "مراکز تفریحی و ورزشی": "RECREATIONAL_SPORTS_CENTERS",
  "آموزش زبان": "LANGUAGE_TEACHING",
  "آموزش آرایشگری": "HAIRDRESSING_TRAINING",
  "لوازم التحریر ": "STATIONERY",
  "گالری ساعت": "WATCH_GALLERY",
  طلافروشی: "GOLD_SALES",
  "اکسسوری زیورآلات": "JEWELRY_ACCESSORIES",
  سوپرمارکت: "SUPER_MARKET",
  لبنیات: "DAIRY",
  "کافه، رستوران و فست فود": "CAFE_RESTAURANT_FAST_FOOD",
  "قنادی و خشکبار": "CONFECTIONERY_DRIED_FRUIT",
  "بیمه آسیا": "ASIA_INSURANCE",
  "بیمه ثالث": "THIRD_PARTY_INSURANCE",
  "پوشاک بزرگسالان": "ADULT_CLOTHING",
  "پوشاک کودکانه": "CHILDREN_CLOTHING",
  "کیف و کفش": "BAGS_AND_SHOES",
  "طراح دکوراسیون داخلی": "INTERIOR_DECORATION_DESIGNER",
  "لوازم ساختمانی": "BUILDING_EQUIPMENT",
};
export const enRoles = {
  پذیرنده: "MERCHANT",
  سازمان: "ORGANIZATION",
  نماینده: "AGENT",
  undefined: "",
};
export const faPositions = {
  نماینده: "AGENT",
  پذیرنده: "MERCHANT",
  سازمان: "ORGANIZATION",
};
export const enPositions = {
  AGENT: "نماینده",
  MERCHANT: "پذیرنده",
  ORGANIZATION: "سازمان",
};
export const faAdminRoles = {
  کارشناس: "EXPERT",
  "مرکز تماس": "CALLCENTER",
  ادمین: "ADMIN",
};
export const enAdminRoles = {
  EXPERT: "کارشناس",
  CALLCENTER: "مرکز تماس",
  ADMIN: "ادمین",
};
export const faTicketList = {
  TECHNICAL: "مشکلات فنی",
  SALES: "بخش فروش",
  ORGANIZATION: "بخش سازمانی",
  MERCHANT: "بخش پذیرنده",
  AGENT: "بخش نمایده",
};
export const enTicketList = {
  "مشکلات فنی": "TECHNICAL",
  "بخش فروش": "SALES",
  "بخش سازمانی": "ORGANIZATION",
  "بخش پذیرنده": "MERCHANT",
  "بخش نمایده": "AGENT",
};
export const roleId = {
  "مرکز تماس": "1c4a5aec-1e6f-4a92-bd80-aa3b423b0ea7",
  کارشناس: "cf4ed568-de52-4615-ad08-85ee06778c2d",
  "کاربر ساده": "f41a4f97-5ee3-4dbe-a97e-b31df9f6a7c4",
  // مدیر: "f41a4f97-5ee3-4dbe-a97e-b31df9f6a7c4",
};
export const zibalStatus = {
  "-1": "در انتظار پردخت",
  "-2": "خطای داخلی",
  "1": "پرداخت شده - تاییدشده",
  "2": "پرداخت شده - تاییدنشده",
  "3": "لغوشده توسط کاربر",
  "4": "شماره کارت نامعتبر می‌باشد",
  "5": "موجودی حساب کافی نمی‌باشد",
  "6": "رمز واردشده اشتباه می‌باشد",
  "7": "تعداد درخواست‌ها بیش از حد مجاز می‌باشد",
  "8": "تعداد پرداخت اینترنتی روزانه بیش از حد مجاز می‌باشد",
  "9": "مبلغ پرداخت اینترنتی روزانه بیش از حد مجاز می‌باشد",
  "10": "صادرکننده‌ی کارت نامعتبر می‌باشد",
  "11": "خطای سویی",
  "12": "کارت قابل دسترسی نمی‌باشد",
};
export const status = {
  FAILED: {
    color: "text-danger bg-danger bg-opacity-30",
    icon: ArrowUpDownFillIcon,
  },
  IN_PROGRESS: {
    color: "text-secondary bg-secondary bg-opacity-30",
    icon: HonourLineIcon,
  },
  ACCEPTED: {
    color: "text-success bg-success bg-opacity-30",
    icon: ArrowUpDownFillIcon,
  },
};
